# platform :ios, ‘8.0’
use_frameworks!

target 'Dolphin' do
    pod 'SDWebImage', '~>3.7'
    pod 'NSDate+TimeAgo'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'TwitterCore'
    pod 'KTCenterFlowLayout'
    pod 'hpple'
    pod 'HMSegmentedControl'
    pod "OAuthSwift", "~> 0.5.0"
end