# platform :ios, ‘8.0’

target 'Dolphin' do
    pod 'SDWebImage', '~>3.7'
    pod 'NSDate+TimeAgo'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'TwitterCore'
    pod 'KTCenterFlowLayout'
    pod 'hpple'
    pod 'HMSegmentedControl'
end